[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install"]

[phases.build]
cmds = ["cd ../.. && cd apps/web && pnpm build"]

[start]
cmd = "cd apps/web && pnpm start"
