[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @printing-workflow/db db:generate",
  "pnpm --filter @printing-workflow/shared build",
  "turbo build"
]

[start]
cmd = "./start.sh"
