[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm build --filter=@printing-workflow/api..."]

[start]
cmd = "pnpm --filter=@printing-workflow/api start"
