[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd ../..",
  "pnpm --filter @printing-workflow/db db:generate",
  "pnpm --filter @printing-workflow/shared build",
  "pnpm --filter @printing-workflow/api build"
]

[start]
cmd = "cd ../.. && ./start.sh"
