[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'cd ../.. && pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'cd ../..',
  'pnpm --filter @printing-workflow/db db:generate',
  'pnpm --filter @printing-workflow/db db:push',
  'pnpm --filter @printing-workflow/api build'
]

[start]
cmd = 'cd ../.. && cd apps/api && pnpm start'
